version: '{build}'
os: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
install:
- ps: >-
    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    .\Install-Dependencies.ps1
before_build:
- ps: msbuild src\pclcrypto\pclcrypto.csproj /t:restore /v:quiet
build_script:
- cmd: >-
    "%programfiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"

    msbuild src\pclcrypto\pclcrypto.csproj /nologo /m /fl /v:minimal /t:build,pack
- ps: Push-AppveyorArtifact msbuild.log
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
#test:
#  assemblies: 'bin\**\PCLCrypto.Tests.Desktop.dll'
