version: '{build}'
os: Visual Studio 2017
skip_tags: true
configuration: Release
environment:
  VisualStudioVersion: 15.0
install:
- ps: >-
    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    # .\Install-Dependencies.ps1
build_script:
- cmd: |
    "%programfiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
    msbuild src /restore /nologo /m /bl:bin\%configuration%\build_logs\msbuild.binlog /v:minimal /t:build,pack
- ps: Push-AppveyorArtifact "bin\$env:configuration\build_logs\msbuild.binlog"
test_script:
- >-
    "%xunit20%\xunit.console.x86.exe"
    bin\PCLCrypto.Tests\%Configuration%\net452\PCLCrypto.Tests.dll
    -html "bin\%configuration%\testresults.html" -xml "bin\%configuration%\testresults.xml"
    -appveyor
    -notrait "TestCategory=FailsInCloudTest"
    -nologo

    dotnet test src\PCLCrypto.Tests --no-build -f netcoreapp1.0

    dotnet test src\PCLCrypto.Tests --no-build -f netcoreapp2.0
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
